## not complete, bullshit
def reverseAndAdd(n):
    return n+int(str(n)[::-1])

lychrel196 = [0]*100000

for x in range(1,100):
    if 196*x>10000:break
    lychrel196[196*x-1]= 1

# the above hash contains numbers generated by 196

cnt = 1
for x in range(197,10000):
    a = x
    count =0
    while count<=50:
        b = reverseAndAdd(a)

        if lychrel196[b-1]:
            cnt+=1
            print cnt
            break
        count+=1
        a = b 
        if a>10000:
            break
